name: Playwright Tests - job triggered by API call
on:
  workflow_dispatch:
    inputs:
      version:
        description: "node version"
        required: false
        default: "22"
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print on console
        run: echo "Running job run-tests"
  final-job:
    runs-on: ubuntu-latest
    needs: [run-tests]
    if: always()
    steps:
      - name: Print on console
        run: echo "final-job of workflow based on node version 18"