name: CI Pipeline

# Event triggers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 2 * * *" # codziennie o 2:00

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint

  changed-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run only changed tests
        run: |
          CHANGED=$(git diff --name-only origin/main...HEAD | grep "tests/.*.spec.ts" || true)
          if [ -z "$CHANGED" ]; then
            echo "No changed tests"
          else
            npx playwright test $CHANGED --reporter=html
          fi
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: changed-tests-report
          path: playwright-report

  regression:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run full regression
        run: npx playwright test --reporter=html
      - name: Upload regression report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-report
          path: playwright-report
