name: Playwright Tests - Master workflow to trigger other workflows
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  running-tests:
    strategy:
      # fail-fast is true by default
      # fail-fast set to true will cancel all jobs if one of them will fail
      fail-fast: false
    uses: ./.github/workflows/simple-jobs.yml # calls other workflow
    secrets: inherit