# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Playwright Smoke Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  run-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:smoke
      - name: Display text on console
        run: echo "Running second workflow for Playwright smoke tests"
      - name: Archive test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with: 
          name: test-reports
          path: |
            ./playwright-report/**/*.*
            ./test-results/**/*.*
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: "./playwright-report/results.xml"