name: Playwright Tests - simple workflow triggered by workflow_call
on:
  workflow_call:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print on console
        run: echo "run-tests of workflow"
  final-job:
    runs-on: ubuntu-latest
    needs: [run-tests]
    if: always()
    steps:
      - name: Print on console
        run: echo "final-job of workflow"